### ISSUE TITLE
What happened to the jre11, jre11-slim & jdk11-slim tags/images?

### ISSUE THREAD

**Issue by chadlwilson** [keeganwitt/docker-gradle#108]
The tags/images for jre11-slim seem to not be published now and there don't seem to be any jdk11-slim images.

jre11 appears to have Dockerfiles but no published images. The slim variants are entirely gone it seems, based on commits. (_Edit: this was an accident, and they have been reinstated - thanks!_)

Is there somewhere I can read the background for why these images are no longer maintained - or understand the normal migration path? I understand that there is a move to `adoptopenjdk` images, which I don't have a concern with, but I'm struggling to figure out how to move from `gradle:5.4.1-jre11-slim` (**376MB**) when the only option appears to be `gradle:5.5.0-jdk11` (**656MB** !!) which is a lot bigger and would appear to include a lot more stuff than the earlier image. 

Adoptopenjdk do maintain upstream `slim` JDK images at least.

I prefer to keep my images as clean as possible; with as few extraneous tools (and potential security vulns) as possible.

I think it would help the community to understand the motivation and expected migration path, and I couldn't figure this out by digging back through commit history, nor the README or Docker Hub page.

**Comment by keeganwitt** [comment]
I discuss that [here](https://github.com/keeganwitt/docker-gradle/issues/104#issuecomment-498713802) and [here](https://github.com/keeganwitt/docker-gradle/pull/101).  As soon as AdoptOpenJDK publishes slim and alpine images on [Docker Hub](https://hub.docker.com/_/adoptopenjdk), I'll happily add them back.

I do apologize for the state of things.  I felt I was left with only sub-optimal options to choose from.

**Comment by chadlwilson** [comment]
Thanks @keeganwitt. As a side note, I personally think the move to AdoptOpenJDK (even for JDK/JRE 11) is a good thing; and their DockerHub release cadence is nice/reliable - much better than Oracle's openjdk builds.

However I'm afraid I'm not quite following - is it do with the the JDK 12 status, that is affecting JDK11 images somehow?

Ignoring the stuff like the missing `git` binaries, the `fonts` issue, and differences between AdoptOpenJDK and regular Oracle JDKs; and ignoring for now whether Alpine images should be used instead of Debian-based images and the musl vs glibc debates that involves
- **jre11** has Dockerfiles in the Gradle repo, but not currently published (jre12 is published). is this just an accidental ommission?
- For Slim JDK images AdoptOpenJDK has both [Debian](https://github.com/AdoptOpenJDK/openjdk-docker/blob/master/11/jdk/ubuntu/Dockerfile.hotspot.releases.slim) and [Alpine slim](https://github.com/AdoptOpenJDK/openjdk-docker/blob/master/11/jdk/alpine/Dockerfile.hotspot.releases.slim) JDK *11* images
- For JRE11 images there are now both [debian](https://github.com/AdoptOpenJDK/openjdk-docker/blob/master/11/jre/debian/Dockerfile.hotspot.releases.full) and [alpine JRE](https://github.com/AdoptOpenJDK/openjdk-docker/blob/master/11/jre/alpine/Dockerfile.hotspot.releases.full) images (we use the Alpine JRE images at runtime for our Java app).

**Comment by chadlwilson** [comment]
OK, I think I kind of see what is going on here. You are preferring the images from the "official" organisation at [adoptopenjdk](https://hub.docker.com/_/adoptopenjdk) whereas the ones I am pointing to (and we are using in our projects) are in the sub-organisations (considered 'community') at https://hub.docker.com/r/adoptopenjdk/openjdk11 and https://hub.docker.com/r/adoptopenjdk/openjdk12 etc. I don't have context on the difference between these, but it does seem they tag them differently, which is rather confusing.

Any reason we can't use the other organisations images rather than the curated "official" images?

**Comment by keeganwitt** [comment]
* The jre11 was an accidental omission, yes.  Thank you for pointing this out.
* The slim and alpine images they have in the adoptopenjdk repo have not been published yet.  You can see the full list of all their latest published images [here](https://github.com/docker-library/official-images/blob/master/library/adoptopenjdk).

Also, keep in mind, these images (and the upstream openjdk images they used) were _not_ Oracle JDK images before moving to AdopOpenJDK, they were using the Debian/Alpine OpenJDK packages.

I'll try again to explain.  When I use the term _openjdk_, I'm referring to the [openjdk](https://github.com/docker-library/openjdk) Docker images, and _OpenJDK_ refers to the [OpenJDK](https://openjdk.java.net/) project.  As you can see in the [documentation](https://github.com/docker-library/official-images#what-do-you-mean-by-official),  official images
> ...strive to create images that are true to the upstream project's vision for how their project is intended to be consumed...

In the case of openjdk, that leadership is Oracle for LTS versions until they hand it off to the leader of the [JDK Updates](https://openjdk.java.net/projects/jdk-updates/) project.  As noted in Red Hat's [blog entry](https://investors.redhat.com/news-and-events/press-releases/2019/04-17-2019-140045508), leadership of the Java 8 and Java 11 updates has been transitioned to Red Hat.  What this means is that Oracle makes decisions on what the openjdk images should be until the hand-off.
Oracle's desire is that the images be based on Oracle Linux.  This means the only non-Oracle Linux images available for an LTS version of Java would be adoptopenjdk until they transition the leadership of the project for that version.  For example, OpenJDK 17 would only be available in adoptopenjdk images and openjdk Oracle Linux images until OpenJDK 18, then Debian based images could be available in the openjdk repo (though I'm not totally sure the project will even choose to do that).

In the interim, before Oracle hands off leadership of an LTS OpenJDK version, I can't use openjdk images as the base image for these gradle images, unless I'm going to have the image switch from being Oracle Linux to Ubuntu once the hand-off happens (which would be too cumbersome to users since they've have to rework commands in downstream Docker files every time that happens) or release versions for both Oracle Linux based openjdk and Ubuntu based adoptopenjdk images (which I thought would be confusing for users).

For non-LTS OpenJDK versions, there are no OpenJDK Updates projects for non-LTS versions, and hence no leadership hand-off.  This means that going forward, there won't be openjdk images for non-LTS OpenJDK versions that aren't based on Oracle Linux.  So OpenJDK 12, 13, 14, 15, and 16 is only available from adoptopenjdk for a Debian/Ubuntu based image unless I transitioned this project to using Oracle Linux, which I think my users would prefer I not do (and would be an even more breaking change than moving to AdoptOpenJDK).

Does that help?

**Comment by keeganwitt** [comment]
Yes, I can't use any community released images for this project.  A rule of the official images project is that you can only use official images as your base image.

**Comment by keeganwitt** [comment]
I've asked about it on their Slack channel: https://adoptopenjdk.slack.com/archives/CERQULPSQ/p1562123311000900.
(You can sign up here: https://adoptopenjdk.net/slack).

**Comment by keeganwitt** [comment]
PR to add JRE 11 image back: https://github.com/docker-library/official-images/pull/6212

**Comment by keeganwitt** [comment]
They do plan to deprecate the non-official images it looked like to me: https://github.com/AdoptOpenJDK/openjdk-docker/issues/185

**Comment by chadlwilson** [comment]
Thanks @keeganwitt - I was possibly misunderstood above - I totally get why you want to move to AdoptOpenJDK and FWIW totally agree with the approach. We came to the same conclusion regarding the core `openjdk` on the project I am currently working on, which is why we are using the AdoptOpenJDK base images for our app (and have been doing so since January 2019).

Anyway, thanks for the explanation and constraints around the "official" images; I wasn't aware of that - but it makes sense. When the `jre11` image re-appears I'll see if this meets our needs - hopefully will.

> They do plan to deprecate the non-official images it looked like to me: [AdoptOpenJDK/openjdk-docker#185](https://github.com/AdoptOpenJDK/openjdk-docker/issues/185)

I asked a clarifying question on that issue, and it seems they only intend to deprecate those also available as official images (which did not exist when we first started using the 'community' images in January), which means only the ubuntu variants as this stage; so it seems the alpine, debian and jdk-slim images will stick around for now.

**Comment by x80486** [comment]
By the way, Zulu's [images](https://hub.docker.com/r/azul/zulu-openjdk-alpine/) is something you might want to consider; they've been generating them for a while – and they are pretty solid.

**Comment by chadlwilson** [comment]
The `gradle:5.5.0-jre11` images are back now, thanks! Having said this, if I understand correctly these are not suitable for us most of the time as we need a Java compiler, and the adoptopenjdk jre base images are 'pure' JRE unlike the older Oracle-owned openjdk images, so currently we have to use the fat JDK variant since we need a compiler in our case.

**Comment by FranklinYu** [comment]
Is there any issue in AdopeOpenJDK repository for us to track the progress?

**Comment by keeganwitt** [comment]
The answer I got from their Slack channel was to ask in GitHub.  The issues I found that seemed like matches were
* https://github.com/AdoptOpenJDK/openjdk-docker/issues/125
* https://github.com/AdoptOpenJDK/openjdk-docker/issues/86

I've added a comment to each to see if we can get some clarity on the status.

**Comment by FranklinYu** [comment]
JRE 11 image on Alpine is available at https://hub.docker.com/r/adoptopenjdk/openjdk11

**Comment by keeganwitt** [comment]
@FranklinYu As mentioned previously, official images are prohibited from having non-official images as their base.  I can't use the image you referenced.

**Comment by bkleef** [comment]
@keeganwitt I'm a bit confused, [adoptopenjdk/openjdk13](https://hub.docker.com/r/adoptopenjdk/openjdk13) has [alpine tags](https://hub.docker.com/r/adoptopenjdk/openjdk13/tags?page=1&name=alpine).
From my understanding this is a non-official image as it is not listed [here](https://github.com/docker-library/official-images/blob/master/library/adoptopenjdk)?

What can we do to merge adoptopenjdk alpine tagged images into `docker-library/official-image`? It looks blocked on https://github.com/AdoptOpenJDK/openjdk-docker/issues/125#issuecomment-534999866?

**Comment by keeganwitt** [comment]
Correct on both counts: I can't use the adoptopenjdk images, as they aren't official (it's a rule all official images must follow), and yes, it appears Alpine images won't be making their way into the official repos until they have a slim build process in AdoptOpenJDK to generate them. I share your disappointment that this won't be landing as soon as originally anticipated.

**Comment by keeganwitt** [comment]
Related discussions:
* https://github.com/AdoptOpenJDK/openjdk-docker/issues/125
* https://github.com/AdoptOpenJDK/openjdk-build/issues/1777
* https://github.com/docker-library/official-images/pull/5710

**Comment by keeganwitt** [comment]
Adding Alpine images in #199. It looks like 11 is there now too (or maybe I missed it before).

**Comment by keeganwitt** [comment]
I'm going to go ahead and close this issue for now. We'll now have the Alpine images, but there's not really anything we can do about the slim images.
