### ISSUE TITLE
Jdk11 image for alpine

### ISSUE THREAD

**Issue by i-wilson** [keeganwitt/docker-gradle#119]
jdk11 is officially available in the alpine pkg repository, could we start pushing images out to dockerhub?

**Comment by i-wilson** [comment]
Just noticed that alpine appears to have been dropped 5 months ago..

**Comment by keeganwitt** [comment]
I'm not happy about the current state of things. But I'm kinda stuck until there's an official Alpine AdoptOpenJDK image to use as the base image for these images (because all official images must have other official images as their base image or be a low level image like a distro).

I discuss the move to AdoptOpenJDK, which unfortunately lost us the Alpine and Slim variants [here](https://github.com/keeganwitt/docker-gradle/issues/108#issuecomment-507918771) and [here](https://github.com/keeganwitt/docker-gradle/issues/104#issuecomment-498713802) (as well as other places).

I'm still hopeful we'll get more options in the future and I'll be able to offer those variants once again. But the timeline isn't very clear at the moment.
