### ISSUE TITLE
Add caches for gradlew

### ISSUE THREAD

**Issue by gaurav517** [keeganwitt/docker-gradle#126]
currently `~/.gradle` directory in docker container is empty. So, if we want to use `gradlew` to build, it would download gradle binary to `~/.gradle` every time a build is run. It delays build process.
If we already have gradle binary cached in `~/.gradle`, `gradlew` won't need to download the binary.

**Comment by keeganwitt** [comment]
The .gradle directory was specifically made a volume so that it could be mounted and retained after the container is destroyed (since in most environments the containers will be ephemeral).

It sounds like in your case, the container(s) are not ephemeral and you are wanting to store the content of that directory in the running container rather than a volume?

If that's the case, Docker doesn't have a way to un-volume a directory, but there are multiple ways Gradle's home directory can be changed to another path (e.g. ~/.gradle2) that is not mounted as a volume, see https://mrhaki.blogspot.com/2010/09/gradle-goodness-changing-gradle-user.html.

**Comment by tbroyer** [comment]
@gaurav517 What's the point of using the `gradle` image if you're going to use the wrapper? I'd say you'd rather use a plain `java` or `adoptopenjdk` image instead.

**Comment by keeganwitt** [comment]
> @gaurav517 What's the point of using the `gradle` image if you're going to use the wrapper? I'd say you'd rather use a plain `java` or `adoptopenjdk` image instead.

I'd agree with this.  If you've decided to use the wrapper, these images aren't going to really provide you any value.

**Comment by gaurav517** [comment]
👍
