### ISSUE TITLE
Prime the wrapper of the same version in the container

### ISSUE THREAD

**Issue by lacasseio** [keeganwitt/docker-gradle#135]
It would be beneficial if the container could already have the wrapper of the same version already configured. Unfortunately, when executing `./gradlew` in a wrapper enabled project, the wrapper downloads the version again.

I could suggest to install Gradle via the wrapper and add that wrapper to the path for the globally installed Gradle. This would allow the best of both worlds.

**Comment by keeganwitt** [comment]
For some context, why would you use this image if you're going to use the wrapper?

The reason I can't do this is that I created a volume in the default Gradle home ( _/home/gradle/.gradle_ (which is also _/root/.gradle_). Volumes are not persisted in Docker images.

Why did I do this? Well, if you wanted to re-use the cached dependencies between builds to save time, you need to be able to persist that part of the container to an external location (i.e. mount the volume) because containers running Gradle tend to be ephemeral (they spin up, do their thing, then are destroyed), so this data needs to exist external to the container.

If you don't need need this (maybe it's a long running container that you re-use or something), you can use a different location that isn't a volume, but passing arguments such as `--gradle-user-home` or `-g` to the Gradle invocation.  For example `./gradlew --gradle-user-home=/root/.gradle-alternate build`.

**Relevant links**
* https://mrhaki.blogspot.com/2010/09/gradle-goodness-changing-gradle-user.html
* https://discuss.gradle.org/t/why-gradle-does-not-use-cache-in-docker/33902
* https://github.com/keeganwitt/docker-gradle/issues/126

**Comment by keeganwitt** [comment]
Closing stale issue.  If you believe there's something that still needs addressed, please comment with more information.
