### ISSUE TITLE
Add support for Gradle 6.7 and java15

### ISSUE THREAD

**Issue by mdiskin** [keeganwitt/docker-gradle#154]
Gradle 6.7 (currently rc-2) will support build on java15
https://docs.gradle.org/6.7-rc-1/release-notes.html#java-15

**Comment by keeganwitt** [comment]
Java 15 isn't yet available in the upstream AdoptOpenJDK image, but should be available shortly.  This should line up pretty close with Gradle 6.7 GA I think.

**Comment by keeganwitt** [comment]
Here's the MR for upstream Java 15 support: https://github.com/docker-library/official-images/pull/8781

**Comment by chris-brace** [comment]
Adoptopenjdk now has hotstop and openj9 images for java 15 :) https://github.com/docker-library/docs/blob/master/adoptopenjdk/README.md#supported-tags-and-respective-dockerfile-links

**Comment by keeganwitt** [comment]
There was a [problem](https://github.com/AdoptOpenJDK/openjdk-docker/issues/445) with those tags. They are based on 20.04 instead of 18.04, which they didn't intend to do just yet. They are going to revert and push 18.04 images, then later upgrade and push with 20.04, but I'm not sure the timing of when my Java 15 images would go out relative to the timing of this re-tagging.  I'll ask the Docker folks how they want to handle.

**Comment by keeganwitt** [comment]
https://github.com/docker-library/official-images/pull/8916
