### ISSUE TITLE
Add support to Gradle 6.6.1 for OpenJ9 (OpenJDK 11)

### ISSUE THREAD

**Issue by afedasenka** [keeganwitt/docker-gradle#155]
Hi,

is it possible to add support for [OpenJ9](https://www.eclipse.org/openj9/)? This is an alternative JVM that is supposed to be faster and more efficient than HotSpot. Thank you in advance

Kind regards,
Alena Fedasenka

**Comment by keeganwitt** [comment]
There's a lot of base images I could include, particularly given all the different JDK flavors that have popped up in the last few years due to Oracle's policy changes.  (e.g. Amazon Corretto and IBM, and all the different variants like Windows images, etc).  The only restriction I have, as an official image, is that the base image must also be an official image.

My own policy had been to keep this project as simple as possible, but if there's a genuine need, I can add it.  Could you help me understand the ask a bit?  Are you aware of performance differences with Gradle on OpenJ9?  If not, are there reasons you can't use Hotspot for compilation, even if the runtime target is OpenJ9?

I'm not rejecting the ask, just want to have clear reasoning for the change (particularly since while I've used different vendors (Red Hat, Amazon, Oracle, AdoptOpenJDK), I've never used anything not Hotspot, so I've got some ignorance here.

**Comment by afedasenka** [comment]
Hi Keegan,

Thank you for your quick response. Of course I can give you a bit of explanation. First of all I cannot give you a proof that Gradle build has performance differences on OpenJ9 compare to the default HotSpot. The team that investigated performance for our services only tested runtime memory usage. And it was determined that we gain good memory usage improvement if we switch our services to OpenJ9 (40% to 50% of the baseline of the default HotSpot)

Many of our services are being built by maven and they use maven Docker image for OpenJ9. So these services now both run and being built on the same jdk (OpenJ9). So we wanted to have consistency and do the same for gradle-based services. But it turned out that it's not officially supported. I tried then to make own docker image for gradle on OpenJ9 and pushed it to our own docker registry (I took as a template one of the official gradle images on JDK 11 and just replaced the FROM value and then locally built a new image). But it didn't work out, in Jenkins pipeline the gradle build failed because of internal gradle/java exceptions. So I decided that my expertise in building images is too limited and on the other hand it's also a custom solution that should be maintained internally. 

For now it was decided that gradle services will be built on the default jdk 11 but will run on OpenJ9. That should not be a problem since all JDKs of the same major version are cross-compatible. But I also decided to ask if it's possible to add an official gradle:openj9 image to central Docker Hub. I am not quite familiar with the policies but decided that's no harm to ask :-)

No matter what you decide, thanks for the interest to the issue and your explanations of quite valid points to be critical to what to add to the list of supported images.

Cheers,
Alena

**Comment by keeganwitt** [comment]
Out of curiosity, what was the error you got?  Because all I'd be doing is flipping the `FROM` and setting up the CI/deployment stuff to go with it (not much more work than you did).  If there's an issue, we probably need to get it raised with the Gradle team (I don't work on the Gradle project itself).  The only issues I'd fix here is if there were some environmental configuration needed (which I doubt is the cause of your problem).

**Comment by keeganwitt** [comment]
Oh, also, which base image did you try?

**Comment by afedasenka** [comment]
Unfortunately the branch where the gradle/java issues appeared is already deleted and I cleaned the docker registry too so I cannot give you a full stack-trace. It was a NullPointerException with long output with an error:
`...
Caused by: java.lang.NullPointerException at org.gradle.api.internal.tasks.compile.JdkTools$DefaultIncrementalAwareCompiler.getStandardFileManager(JdkTools.java:137)
...`

The base Dockerfile I took was that one https://github.com/keeganwitt/docker-gradle/blob/f6e27a40b3c8b6dcc8dc07a278f7a9f0c2a808cb/jdk11/Dockerfile. I changed the FROM value to adoptopenjdk:11.0.8_10-jre-openj9-0.21.0

**Comment by keeganwitt** [comment]
Oh, I just noticed one possible explanation: you used a JRE image.  A JDK image is necessary to do Java compilation.  I swapped in `FROM adoptopenjdk:11-jdk-openj9` on the [JDK 11 Dockerfile](https://github.com/keeganwitt/docker-gradle/blob/master/jdk11/Dockerfile) and tested it against my [java-quickstart](https://github.com/keeganwitt/docker-gradle/tree/master/test/java-quickstart).  It worked for me.

**Comment by afedasenka** [comment]
> Oh, I just noticed one possible explanation: you used a JRE image. A JDK image is necessary to do Java compilation. I swapped in `FROM adoptopenjdk:11-jdk-openj9` on the [JDK 11 Dockerfile](https://github.com/keeganwitt/docker-gradle/blob/master/jdk11/Dockerfile) and tested it against [java-quickstart](https://github.com/keeganwitt/docker-gradle/tree/master/test/java-quickstart). It worked for me.

Oh yeah, that explains the issue. And as far as I understand you decided eventually to add more images. Thanks a lot for that!

**Comment by keeganwitt** [comment]
I'd be curious to hear any changes in performance characteristics you noticed.  I've seen several blogs about performance in production runtimes, but I've never seen anyone comment on compilation performance.

**Comment by afedasenka** [comment]
Thanks a lot for adding the OpenJ9 images. I'll update you if we detect performance differences during the compile time
