### ISSUE TITLE
amd64 version missing of gradle:6.8.0-jdk11 (and possible others)

### ISSUE THREAD

**Issue by JoepWeijers** [keeganwitt/docker-gradle#172]
I am not able to use the newly released gradle 6.8.0 Docker images:
```
>docker pull gradle:6.8.0-jdk
6.8.0-jdk: Pulling from library/gradle
no matching manifest for linux/amd64 in the manifest list entries
````

And indeed on the Docker Hub tags, there is no linux/amd64. The `-openj9` version has even less different platforms. Did something go wrong or am I too impatient and are they still in the pipeline?

**Comment by keeganwitt** [comment]
I have disabled Openj9 Java 15 builds because of an Openj9 [bug](https://github.com/eclipse/openj9/issues/11013). I think the fix hasn't been released into the upstream Docker image yet.

I was able to pull the amd64 image just now. It looks to me like their Jenkins job ran again (https://doi-janky.infosiftr.net/job/multiarch/job/amd64/job/gradle/). Can you try again?

**Comment by JoepWeijers** [comment]
Pulling `gradle:6.8.0-jdk` works, thanks for fixing it!

**Comment by keeganwitt** [comment]
I didn't actually do anything :) The Docker Library folks manage the pipeline for this. But glad it's back working again.
