### ISSUE TITLE
Consider keeping 6.x alongside 7.0

### ISSUE THREAD

**Issue by tbroyer** [keeganwitt/docker-gradle#182]
It's [been announced](https://twitter.com/CedricChampeau/status/1380431356174479361) that there will be a Gradle 6.9 line alongside Gradle 7.0, so I think this repository, and particularly the Official Images, should retain both the 6.x and 7.0 release lines.

Keeping 6.8.3 for now (pending a 6.9) would also mean that Docker rebuilds those whenever the underlying adoptopenjdk image is updated; but otherwise I think this could wait for the actual 6.9 release.

**Comment by keeganwitt** [comment]
FYI, removing the 6.8.3 tag from https://github.com/docker-library/official-images doesn't delete the image from Docker Hub, the image just won't be updated in the future (for example re-tagged when a new Java version comes out).

Thanks for mentioning 6.9, I missed that announcement. I think what I'll do is add a new branch for 6.x when 6.9 comes out.

No one has asked for it yet, but I'd also consider other branch strategies so make beta and RC versions available as well, which would include 6.9 if there was interest.

**Comment by Legogris** [comment]
This would be great. A couple of community projects I'm using started failing to build due to changes in gradle7 and it would help users a lot to have an obvious way to base images off 6.x instead of 7 until the underlying issues are addressed

**Comment by keeganwitt** [comment]
They don't show up on the [main page](https://hub.docker.com/_/gradle?tab=description) yet because I haven't done an update to add them back, but the 6 tags are [still present](https://hub.docker.com/_/gradle?tab=tags&page=1&ordering=last_updated&name=6.8).

I'm thinking that all the non-versioned tag s (e.g. jdk8, jdk8-hotspot, jdk, jdk-hotspot, latest, hotspot) will remain pointed to the latest Gradle (7.0), but we'll also have the usual numbered tags like 6.9.0-jdk8, 6.9.0-jdk8-hotspot, 6.9-jdk8, 6.9-jdk8-hotspot, 6.9.0-jdk, 6.9.0-jdk-hotspot, 6.9-jdk, 6.9-jdk-hotspot, 6.9.0, 6.9.0-hotspot, 6.9, 6.9-hotspot once 6.9 is released. That seemed like the most intuitive strategy to me (feel free to chime in if you have other ideas).

Maybe I should update the page to still list 6.8. I kinda assumed 6.9 would be coming out fairly quickly and I could just update it in one go, but I haven't actually heard when 6.9 will be landing, so maybe that's an incorrect assumption.

**Comment by Legogris** [comment]
Ultimately your call but I would suggest doing what most distros and languages do, e.g. have a prefix of only the major version as the leading part of the label (so e.g. `6-jdk11`) since that's when braking changes are the most likely to be introduced and the breaking point of when manual intervention should be expected on upgrades

**Comment by keeganwitt** [comment]
I thought about that. I think at the time I first decided on the current tagging strategy, it seemed like breakages were more common between minor versions. But that was several years ago and these days it seems like Gradle is closer to semantic versioning now than it was then. I suppose I could add those tags now, though it might be a bit odd, since no version has ever been tagged without the minor version before (though that's not a strong reason _not_ to do it).

**Comment by keeganwitt** [comment]
https://github.com/docker-library/official-images/pull/10054
