### ISSUE TITLE
Missing jdk 12/13/14

### ISSUE THREAD

**Issue by bitbaggi** [keeganwitt/docker-gradle#185]
Heyho,

are there plans to add docker images for jdk 12/13/14?

Greetings

**Comment by keeganwitt** [comment]
No, I did not plan on adding those because they are no longer supported/updated by AdoptOpenJDK: https://adoptopenjdk.net/support.html.

Does that cause an issue? I think the best practice is to use the latest version of the JDK and move on to the next one once that's no longer supported. If you can't do that, you should consider an LTS version instead.

**Comment by keeganwitt** [comment]
Since I haven't heard an objection to the current strategy, closing for now.
