### ISSUE TITLE
support arm64 architecture

### ISSUE THREAD

**Issue by longquan7** [keeganwitt/docker-gradle#23]
https://services.gradle.org/distributions/gradle-${GRADLE_VERSION}-bin.zip
I want to build this image on arm64 architecture but I'm not sure this file can be support arm64 architecture

**Comment by keeganwitt** [comment]
I'm honestly not sure either.  I'd suggest asking on the [Gradle Forums](https://discuss.gradle.org/).

**Comment by tianon** [comment]
Since `gradle` is `FROM openjdk:...`, this `Dockerfile` _should_ just work as-is with any the architectures supported by `openjdk` (https://github.com/docker-library/official-images/blob/83445dba81738f34d37e13fa811b34841d1d6def/library/openjdk#L63, `amd64, arm32v5, arm32v7, arm64v8, i386, ppc64le, s390x`), with the caveat that Alpine support needs to wait on https://github.com/gliderlabs/docker-alpine/issues/304.

See https://github.com/docker-library/official-images#architectures-other-than-amd64 and https://github.com/docker-library/official-images#multiple-architectures for more information about multi-architecture official images. :+1:

**Comment by keeganwitt** [comment]
Thanks @tianon!  As far as I know, I'd expect it should just work also.  I'm not sure if Gradle's native compilation stuff has any limitations though, I've never used Gradle in that way.

**Comment by lag-linaro** [comment]
Indeed this image does "just work" on ARM64.  I just built and tested it.

Could we please tag this to work on ARM64 in the [Official Images](https://github.com/docker-library/official-images) repo, so `docker pull gradle` will "just work" too.

**Comment by lag-linaro** [comment]
Also, could someone re-open this issue until resolved please?

**Comment by keeganwitt** [comment]
I've made the request to official-images: https://github.com/docker-library/official-images/pull/4451.

**Comment by lag-linaro** [comment]
You're a star.  Thank you.
