### ISSUE TITLE
JDK20 image missing

### ISSUE THREAD

**Issue by jurriaan** [keeganwitt/docker-gradle#247]
The jdk20 images are missing on dockerhub, can they be released?

**Comment by keeganwitt** [comment]
As I noted in the PR that added the images (#245), the latest (8.1.1) [release notes](https://docs.gradle.org/8.1.1/release-notes.html#jvm) say
> Gradle now supports using Java 20 for compiling, testing, and starting other Java programs. This can be accomplished by configuring your build or task to use a Java 20 [toolchain](https://docs.gradle.org/8.1.1/userguide/toolchains.html).
>
> You cannot currently run Gradle on Java 20 because Kotlin lacks support for JDK 20. However, you can expect support for running Gradle with Java 20 in a future version.

They also note this in their [compatibility guide](https://docs.gradle.org/current/userguide/compatibility.html). This is why I have not yet published the Java 20 images to Docker Hub.

So In order to compile targeting Java 20, you'd need a Docker image with both Java 8, 11, or 17 and Java 20. This Docker image hasn't ever published images with multiple versions of Java on it. My hope was that full Java 20 support was coming soon, but it sounds like it might not be until 8.2 (July). See the issue [here](https://github.com/gradle/gradle/issues/23488). You can also follow the Kotlin [issue](https://youtrack.jetbrains.com/issue/KT-57495/Add-JVM-target-bytecode-version-20) issue. I'm not sure which Scala issue(s) are relevant yet.

**Comment by keeganwitt** [comment]
I think a 17-based image that has 20 also installed for use with a toolchain actually isn't as complicated to do as I originally thought (once the idea of a multi-stage image occurred to me). #248 If there's interest, let me know.

**Comment by keeganwitt** [comment]
They're not published into Docker Hub yet because

* I haven't merged #248
* Gradle 8.3 which will fully support Java 20 hasn't been released yet (but I think they're very close since RC4 was just a few days ago)

I was trying to avoid merging #248 since it's another image to maintain and Gradle 8.3 wasn't far off. But if there are folks that really need it, I can. Just let me know.

To clarify what's needed for Java 20 with Gradle 8.1/8.2: You have to start Gradle with Java 11/17, then use Java 20 in a toolchain to target Java 20 bytecode. That's what the image in #248 was about: an image that ships multiple JDKs.

**Comment by JohannesLichtenberger** [comment]
Hmm, wasn't aware of this, but the gradle wrapper with Gradle 8.2.1 seems to work with Java 20... but have only tried with IntelliJ so far and executing the unit tests / integration tests.

**Comment by JohannesLichtenberger** [comment]
This is the Dockerfile: https://github.com/sirixdb/sirix/blob/master/Dockerfile

**Comment by JohannesLichtenberger** [comment]
I'd also go with a GraalVM based image as in tests the new version for Java 20 was really way faster in one test with a huge import file (meaning 60s instead of roughly 100s to import a close to 4Gb JSON file). Still, with async flushes to disk in the future it should be faster, but at least we managed to import also with only 8Gb RAM on one machine, whereas with MongoDB it doesn't seem possible to import at all.

**Comment by keeganwitt** [comment]
I've heard similar anecdotes, though I can't speak to it from personal experience. As an official image, my policy has to be to follow the official recommendations/statements from the Gradle team themselves. If I were to publish the Java 20 image that I have in this repo, it'd have to be to an unofficial location in Docker Hub.

Also keep in mind, Java 19 [is EOL](https://endoflife.date/java), which is why this project is no longer publishing updates to those images.

**Comment by keeganwitt** [comment]
> I'd also go with a GraalVM based image as in tests the new version for Java 20 was really way faster in one test with a huge import file (meaning 60s instead of roughly 100s to import a close to 4Gb JSON file). Still, with async flushes to disk in the future it should be faster, but at least we managed to import also with only 8Gb RAM on one machine, whereas with MongoDB it doesn't seem possible to import at all.

Once https://github.com/docker-library/official-images/pull/15214 is merged, GraalVM images should be in a usable state.

**Comment by JohannesLichtenberger** [comment]
Is it GraalVM for Java 20 and Gradle 8.2.1? The GraalVM images as of now don't seem to have a Java version in the tag name IIRC. All in all it seems I have to wait for Gradle 8.3 (luckily it's a spare time project since the last 10 years ;-))

**Comment by keeganwitt** [comment]
> Is it GraalVM for Java 20 and Gradle 8.2.1? The GraalVM images as of now don't seem to have a Java version in the tag name IIRC. All in all it seems I have to wait for Gradle 8.3 (luckily it's a spare time project since the last 10 years ;-))

No. There are no Java 20 images of any kind yet because Gradle doesn't support it until 8.3. The only other option is the dual-JDK of #248.

**Comment by JohannesLichtenberger** [comment]
I don't know if that means I'd have to change other parts of the `Dockerfile` in SirixDB. Maybe not, but otherwise I'd leave it for now, as I yesterday started a new job as an embedded software engineer, meaning I will not have much time to work on Sirix right now...

**Comment by keeganwitt** [comment]
> I don't know if that means I'd have to change other parts of the `Dockerfile` in SirixDB. Maybe not, but otherwise I'd leave it for now, as I yesterday started a new job as an embedded software engineer, meaning I will not have much time to work on Sirix right now...

The Dockerfile no, but the Gradle files yes (for some users). It looks like you have that change already though. See [here](https://github.com/keeganwitt/docker-gradle/blob/gradle_8.1_java20/README.md#java-20-with-gradle-81-or-82).

**Comment by keeganwitt** [comment]
8.3 just got released this morning!

**Comment by keeganwitt** [comment]
> Yay, do you push the images?

https://github.com/docker-library/official-images/pull/15221

**Comment by JohannesLichtenberger** [comment]
I've updated the Dockerfile, but I guess it needs some time until they are on docker.io

**Comment by JohannesLichtenberger** [comment]
https://github.com/sirixdb/sirix/blob/master/Dockerfile

**Comment by keeganwitt** [comment]
> I've updated the Dockerfile, but I guess it needs some time until they are on docker.io

They haven't merged my PR yet that would kick off the build and push.
