### ISSUE TITLE
arm64 alpine images are missing

### ISSUE THREAD

**Issue by Julian** [keeganwitt/docker-gradle#258]
Attempting to run a container using the alpine image fails on a Mac M1 with:

```
⊙  podman run --rm -it gradle:8.3-jdk17-alpine
Resolving "gradle" using unqualified-search registries (/etc/containers/registries.conf.d/999-podman-machine.conf)
Trying to pull docker.io/library/gradle:8.3-jdk17-alpine...
Error: choosing an image from manifest list docker://gradle:8.3-jdk17-alpine: no image found in manifest list for architecture arm64, variant "v8", OS linux
```

This seems similar to #66.

**Comment by keeganwitt** [comment]
This is intentional. The file for this image is here: https://github.com/docker-library/official-images/blob/master/library/gradle

You can see it currently has
```
Tags: 8.3.0-jdk17-alpine, 8.3-jdk17-alpine, 8-jdk17-alpine, jdk17-alpine, 8.3.0-jdk-alpine, 8.3-jdk-alpine, 8-jdk-alpine, jdk-alpine, 8.3.0-alpine, 8.3-alpine, 8-alpine, alpine
Architectures: amd64
GitCommit: f2462744bc16e4c55fd53fba45e9d4c46d8417de
Directory: jdk17-alpine
```

This is because the upstream image (https://github.com/docker-library/official-images/blob/master/library/eclipse-temurin) only publishes the Java 17 Alpine image for amd64
```
Tags: 17.0.8.1_1-jdk-alpine, 17-jdk-alpine, 17-alpine
Architectures: amd64
GitCommit: 25f458a0991f58bb7ed0ec9817e026a40d559c38
Directory: 17/jdk/alpine
File: Dockerfile.releases.full
```

If Eclipse Temurin provides this image, I'll be happy to provide the Gradle image using it. There's a long-running issue on this: https://github.com/adoptium/containers/issues/158.

Sorry that we're stuck for now.

**Comment by callumhauber** [comment]
It looks like the jdk 21 alpine image has support for arm64v8 now (https://github.com/docker-library/official-images/blob/master/library/eclipse-temurin#L364-L365)
```
Tags: 21.0.2_13-jdk-alpine, 21-jdk-alpine, 21-alpine
Architectures: amd64, arm64v8
GitCommit: 5ef325612fc29e529a339ea7e35e4183cf9ae888
Directory: 21/jdk/alpine
```
