### ISSUE TITLE
gradle:8.6.0-jdk* vulnerabilities

### ISSUE THREAD

**Issue by chekmx** [keeganwitt/docker-gradle#278]
sysdig reports the following vulnerabilities for container gradle:8.6.0-jdk*

- CVE-2023-44487
- CVE-2023-4785
- CVE-2023-33953
- CVE-2023-43804
- VULNDB-322362
- CVE-2023-45803
- CVE-2023-32732
- VULNDB-349788
- VULNDB-349787
- VULNDB-298175

Is it possible to remediate these?

**Comment by yosifkit** [comment]
🤔 `8.6.0` is no longer a supported version (and so is not rebuilt in official images), so it is likely to have more outdated packages over time.  I'd suggest updating to `8.7` (built just a few days ago) or just doing an `apt-get update && apt-get upgrade` in your own image if you cannot move to the latest.

Background: 
>Tags in the [official-images] library file[s] are only built through an update to that library file or as a result of its base image being updated (ie, an image `FROM debian:buster` would be rebuilt when `debian:buster` is built). 
>
>\-https://github.com/docker-library/official-images/tree/2f086314307c04e1de77f0a515f20671e60d40bb#library-definition-files

Official Images FAQ:

> Though not every CVE is removed from the images, we take CVEs seriously and try to ensure that images contain the most up-to-date packages available within a reasonable time frame
>
> \- https://github.com/docker-library/faq/tree/0ad5fd60288109c875a54a37f6581b2deaa836db#why-does-my-security-scanner-show-that-an-image-has-cves

To ensure that we don't push contentless image changes, we rely on periodic base image updates. Debian and Ubuntu are (mostly) on a ~30 day rebuild cycle so that base image packages are updated and that all dependent images are also rebuilt for OS packages included there.

> We strive to publish updated images at least monthly for Debian. We also rebuild earlier if there is a critical security need. Many Official Images are maintained by the community or their respective upstream projects, like Ubuntu, Alpine, and Oracle Linux, and are subject to their own maintenance schedule.
>
> \- from the same FAQ link

**Comment by keeganwitt** [comment]
At the time the ticket was opened, 8.6 was the latest. 8.7 was released the next day.

That being said, @chekmx should check whether these are still reported in the 8.7 images, as these will contain the latest security patches as has been noted.

**Comment by chekmx** [comment]
Having checked 8.7 I see that all the vulnerabilities listed above still exist except https://github.com/advisories/GHSA-v845-jxx5-vc9f .  

Further I see the following new items
CVE-2023-43804
CVE-2020-13956
CVE-2023-45803
CVE-2023-48795
CVE-2023-32732

**Comment by keeganwitt** [comment]
I wasn't sure if the grpc one referred to a jar or not. there is
```
$ docker run --rm gradle bash -c 'find /opt/gradle -name *.jar | grep grpc'
/opt/gradle/lib/plugins/grpc-context-1.27.2.jar
```
Since there's nothing installed by apt, I'm going to guess this comes from the Gradle zip. If so, it will be up to the Gradle team to remediate.

The HTTP Client shouldn't be showing up in your scan. The CVE says it affects versions before 4.5.13 and 5.0.3. The version included is 4.5.14.
```
$ docker run --rm gradle bash -c 'find /opt/gradle -name *.jar | grep httpclient'
/opt/gradle/lib/plugins/httpclient-4.5.14.jar
```

**Comment by keeganwitt** [comment]
Actually, looking in grpc-context-1.27.2.jar, I don't see any compiled native files, so I think this is a false positive as well.

**Comment by keeganwitt** [comment]
I believe we've addressed all the concerns. Reply if you think this needs re-opened.
