### ISSUE TITLE
s390x platform version missing for 8.7.0

### ISSUE THREAD

**Issue by alexwoodgate** [keeganwitt/docker-gradle#284]
I'm unable to pull the linux/s390x platform version of the 8.7.0 Gradle image. I'm fairly sure this was working when my team first updated to FROM that version but now get failures pulling it. The Dockerhub pages don't list the platform for 8.7.0 either, but it's still listed as supported on the Dockerhub overview page.

Was there a change which removed support or an error building those images?
It looks like linux/arm/v7 and linuxx/ppc64le are also missing when comparing 8.7.0 to 8.6.0

Failing pull for 8.7.0:
```
podman pull --platform linux/s390x gradle:8.7.0
Resolving "gradle" using unqualified-search registries (/etc/containers/registries.conf.d/999-podman-machine.conf)
Trying to pull docker.io/library/gradle:8.7.0...
Error: choosing an image from manifest list docker://gradle:8.7.0: no image found in manifest list for architecture s390x, variant "", OS linux
```

Successful pull for 8.6.0:
```
podman pull --platform linux/s390x gradle:8.6.0
Resolving "gradle" using unqualified-search registries (/etc/containers/registries.conf.d/999-podman-machine.conf)
Trying to pull docker.io/library/gradle:8.6.0...
Getting image source signatures
Copying blob sha256:3b71ed0a6b0974e6a85ebcf0714bb9f92a1f0de7936b00bc89fdea0082c08815
...
```

**Comment by keeganwitt** [comment]
Apologies for the confusion. This is because I moved the latest tags to use Java 21 instead of 17. My intention was that the latest tag would always point to the latest LTS Java.
https://github.com/docker-library/official-images/pull/16537

There is, unfortunately, no upstream s390x for Java 21. This means you need to use the Java 17 image (using one of the tags below).
* 8.7.0-jdk17
* 8.7-jdk17
* 8-jdk17
* jdk17
* 8.7.0-jdk17-jammy
* 8.7-jdk17-jammy
* 8-jdk17-jammy
* jdk17-jammy
