### ISSUE TITLE
Gradle in re-downloading images in child images

### ISSUE THREAD

**Issue by mikegleasonjr** [keeganwitt/docker-gradle#30]
Hi, I have these images:

image1
 
```
FROM gradle:jdk8-alpine
RUN ["sh", "-c", "gradle clean build distTar"]
```
(downloads dependencies)
.
.
.

Image2

```
FROM image1
CMD gradle clean test
```
(downloads dependencies again)
.
.
.

When `image2` builds right after `image1`, it re-downloads dependencies. Shouldn't the deps be embedded in `image1`?

Pretty new to docker.

**Comment by keeganwitt** [comment]
I made the .gradle directory a Docker [volume](https://docs.docker.com/engine/admin/volumes/volumes/) specifically so that you could do things like re-use cached dependencies even if you destroy and create a new container each time, or have 2 containers both using the cache (although the Gradle guys mentioned there are some lock contention issues with that usage currently).  Volume do this by writing the data outside the container.  To save the data, just tell Docker where you want it saved (see [reusing the gradle cache](https://github.com/keeganwitt/docker-gradle/blob/master/README.md#reusing-the-gradle-cache)).

This is a common pattern.  For example, the Mongo Docker image stores the database data in a volume so your data doesn't get deleted when you rebuild a container.

**Comment by mikegleasonjr** [comment]
@keeganwitt thanks for the detailed explanations
