### ISSUE TITLE
cache folder empty on build

### ISSUE THREAD

**Issue by FernandoMiguel** [keeganwitt/docker-gradle#43]
I have a cache docker builder that will download the resources and build a cache
```
FROM gradle:jdk8-alpine as cache-builder

#  gradle docker runs with gradle user and files are copied as root
USER 0
WORKDIR /src
COPY . /src
RUN gradle assemble --no-daemon --build-cache
```

later the cache is used to copy to another multistage docker.
```
FROM gradle:jdk8-alpine as builder

EXPOSE 8080

#  gradle docker runs with gradle user and files are copied as root
USER 0
WORKDIR /src
COPY --from=cache-builder /home/gradle/.gradle/caches /home/gradle/.gradle/caches
COPY . /src
RUN gradle clean assemble --offline --no-daemon


FROM openjdk:8-jre-alpine as app
WORKDIR /app
CMD java -jar ./app.jar application.yml
COPY --from=builder /src/build/libs/*.jar /app/app.jar

ARG RELEASE_ENV
ENV RELEASE_ENV_ARG=$RELEASE_ENV
COPY config/application.yml.$RELEASE_ENV_ARG /app/application.yml
```

if i doc docker run cache-builder, and run `gradle assemble --no-daemon --build-cache` it will save the cache in `/home/gradle/.gradle/caches`
But when i try to do docker build of the `cache-builder` and later try to copy , the folder is empty.

Not sure if it is caused because that mountpoint is a docker volume?
Should i change the location where the cache is saved?

Thanks in advance

**Comment by keeganwitt** [comment]
Did you mount the cache to a volume?  And what process is copying files as root that makes you need to change to root user?

**Comment by FernandoMiguel** [comment]
@keeganwitt no volume mount given that `cache-builder` never actually runs, it's only created during build.
I worked around by using another location , other than the default one where you use a volume.
I suspect the limitation comes from `docker build` not having access to a volume

**Comment by pmiklos** [comment]
I am struggling with a similar issuer. I am extending this image to build my project. To optimize consecutive builds I call gradle build twice with a RUN command: once to build the cache, second to build my project sources. The problem is at the second run `/home/gradle/.gradle` folder is empty so the optimization doesn't work. I think it's because this image defines `/home/gradle/.gradle` as a volume so when the intermediate container is created for each layer everything saved in the volume is dropped when the container is dropped and a new one created for the next layer.

This is roughly what I am doing as the build part of a multistage  Dockerfile:
```
FROM    gradle:4.5-jdk8 AS BUILD_IMAGE

COPY    --chown=gradle:gradle build.gradle .
RUN     gradle build  # download deps, builds cache in /home/gradle/.gradle

# at this point/home/gradle/.gradle content dropped here because it's a volume

COPY    --chown=gradle:gradle . $SRC
RUN     gradle build  # sadly it downloads dependencies again, since the cache is empty
```

**Comment by keeganwitt** [comment]
@pmiklos That's correct. Docker regards the data in a volume as transient, and it will not be written into image layers.  The reason I made it a volume was so that you could mount it to a location outside the container so that you don't have to have every container instance download all the dependencies again.

Currently it's [not possible](https://github.com/moby/moby/issues/3465) to override the volume declaration of the parent.  However, if you really need the dependencies in the image itself, you could create a new user, which will have it's own cache directory that you could leave as a non-volume, then it'd be included in a layer.

**Comment by pmiklos** [comment]
Making the gradle cache as a volume is very useful when the gradle container is used as an app, but not so much when the image is used as a base to build a project inside the container. Maybe just mention it in the docs somewhere, that would save some time for those who use it for the latter use case. I managed to resolve my issue using `--gradle-user-home` and pointing it to a different directory when running the gradle build.

**Comment by keeganwitt** [comment]
I've updated the readme, as requested.
