### ISSUE TITLE
Images for Gradle 4.10.2

### ISSUE THREAD

**Issue by alesbukovsky** [keeganwitt/docker-gradle#71]
The repo seems to be updated with 4.10.2, but I see no relevant tags and images in Docker Hub. It still has 4.10.1 the latest. Any ETA when 4.10.2 will be available? Thanks.

**Comment by keeganwitt** [comment]
I'd made a change to download the sha from Gradle's server instead of putting the sha into the Dockerfile myself.  There was some discussion about this on my [PR](https://github.com/docker-library/official-images/pull/4859) and we decided the original behavior should be retained for improved security, so I put it back in a subsequent commit.  This delayed the PR from being merged, it got merged just 3 hours ago and should be available on Docker Hub now.
