### ISSUE TITLE
JDK 12 support

### ISSUE THREAD

**Issue by dje1990** [keeganwitt/docker-gradle#91]
Will JDK 12 be supported by the docker-gradle image? Thanks

**Comment by keeganwitt** [comment]
It's my plan to support it as soon as an image with the Linux version (Alpine/Debian) I publish for is available from my base image ([openjdk](https://hub.docker.com/_/openjdk/)). Currently the only Java 12 images available for me to build on top of are Oracle Linux and Windows.

**Comment by dje1990** [comment]
Ok thanks @keeganwitt I will check back again in a few days. Thanks.

**Comment by keeganwitt** [comment]
I'm not sure if it will be done quickly.  I know the Docker guys need to have Alpine/Debian package maintainers create a new package so they can use it in their Docker image as well.  I'm not sure yet how far those maintainers are with that.

**Comment by davidkarlsen** [comment]
https://github.com/keeganwitt/docker-gradle/pull/92

**Comment by vvanholl** [comment]
@davidkarlsen This is not as simpler as it looks

You have differences between openjdk:11-jdk and openjdk:12-jdk
First : wget and unzip are absent, you need install them
Then : LANG environment variable is not set

**Comment by hc-codersatlas** [comment]
Maybe better to use AdoptOpenJDK images? 12 is already there.

**Comment by keeganwitt** [comment]
There's a discussion on this in the openjdk image repo: https://github.com/docker-library/openjdk/issues/302.  Tianon asked that folks who think we need an official OpenJDK image based on Debian in addition to Oracle Linux respond with thumbs up to [this comment](https://github.com/docker-library/openjdk/issues/302#issuecomment-482722509).  I think there are likely images folks have made with the Debian based Gradle image as a base image that would take significant migration to move to Oracle Linux.  So I think it's a +1 for users of this image.

For this image, we could add Oracle Linux in _addition_ to Debian and Alpine based images, but not as a replacement for either.

The AdoptOpenJDK images, while closer than Oracle Linux, aren't a perfect replacement either since they're based on Ubuntu rather than Debian.  But their Alpine images might be a potential replacement for the official OpenJDK Alpine images.

Another option would be for me to install both OpenJDK tarball and Gradle into a vanilla Debian image.  I think either this or the AdoptOpenJDK option are gonna be the way to go.  I don't know when we'll get an OpenJDK 12+ image we can use.

**Comment by keeganwitt** [comment]
My discussion with folks at Docker suggested AdoptOpenJDK is a better approach since that team tests against Ubuntu, and thus will be closer to upstream than a manually installed tarball by us.  I like that it's less for me to maintain, though it does change the base from Debian to Ubuntu.  For the time being, that's the direction I'll proceed with.

**Comment by keeganwitt** [comment]
Actually, we have to wait until AdoptOpenJDK is available as an official base image (https://github.com/docker-library/official-images/pull/5710) before this can go live.
