### ISSUE TITLE
Why does the gradle image run by default as a gradle user?

### ISSUE THREAD

**Issue by XhstormR** [keeganwitt/docker-gradle#93]
I searched Google and found that many people made mistakes because of this line of code. And I use Drone CI Service to start gradle image to build software, cannot specify a image to run as root , so this problem is very difficult to solve.

```
USER gradle
```

I use the gradle:latest image, the solution I used  is copy to home dir, but is just a workaround, there are many inconveniences for the latter operations.
```
- cp -R . ~/src
- cd ~/src
- ./gradlew assemble
```

Now i switched to the openjdk:latest image, which runs as root by default. just:
```
- ./gradlew assemble
```

**Comment by XhstormR** [comment]
[This link](https://discuss.gradle.org/t/docker-image-permission-issue/25149) has more information if you need it.

**Comment by keeganwitt** [comment]
It's a security best practice, see
* https://success.docker.com/article/security-best-practices#containeruidmanagement
* https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#user
* https://engineering.bitnami.com/articles/best-practices-writing-a-dockerfile.html#using-the-non-root-approach-to-enforce-container-security
* https://engineering.bitnami.com/articles/why-non-root-containers-are-important-for-security.html

I'm struggling with how to do the right thing here.  There are users that are stuck because of functional deficiencies in their CI, but if I change the default user to root, then those same CIs can't avoid running as root.

**Comment by keeganwitt** [comment]
I'm considering a compromise here.  To help me make an informed decision, is it possible to run Docker from a command (e.g. `docker run ...`) in Drone CI?  Or can commands only be run in the context of an image?

**Comment by XhstormR** [comment]
As far as I know, in Drone CI, you can't customize the parameters of the docker run command yourself, you can only configure it by specifying the docker parameter exposed in the yaml syntax configuration.

[This document](https://docs.drone.io/user-guide/pipeline/steps/#commands) describes the docker run parameters that support configuration.

In the latest commit, the yaml configuration defines the `user` syntax, which can be specify a user  to run the current image, but I have not tried it yet.

**Comment by hawkesnc** [comment]
I need the ability to run as root as well.

I'm using gradle with the jib plugin. It requires installing additional docker credential helpers (https://github.com/GoogleContainerTools/jib/tree/master/jib-gradle-plugin#using-docker-credential-helpers) so it can directly upload containers to the registries. When not on root, I can't install these additional packages

**Comment by keeganwitt** [comment]
But it is possible to use Gitlab runner to run as root if needed, using the shell provisioner, right?  I'm just trying to understand the scope of the problem and how onerous the existing workarounds are.

**Comment by XhstormR** [comment]
I ended up switching to the Gitlab runner to run the gradle image, using the [official gradle CI template](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/lib/gitlab/ci/templates/Gradle.gitlab-ci.yml), and not specifying the running user, and no errors occurred : )

**Comment by kudos** [comment]
@keeganwitt a lot of images seem to follow a practice like this https://www.linuxserver.io/docs/puid-pgid/. Essentially it runs as root to bootstrap the container, but quickly drops privileges to either 1000:1000 (whatever username that might be), or the UID/GID extracted from the environment.

**Comment by jjinux** [comment]
Supporting those environmental variables would be a nice improvement.

**Comment by keeganwitt** [comment]
In order to support the environment variables, I'd have to change the entrypoint to run a script to create the requested uid/gid (it looked like they used an S6 overlay for this).

If folks truly need the image to default to running as root, I'll make the change.  But I want to be sure it's necessary, both because non-root is better security practice, and because making this change can potentially break other users.  If you require this, please describe your use case so I have some justification for this change.

**Comment by disparo13** [comment]
When I'm trying to use the native gradle image for Gitlab CI, my build failing with 

`FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'project'.
> /builds/projectfolder/project/.git/hooks/pre-commit (Permission denied)
`
As I guess, its because of using of the pre-commit hook in my build.gradle which trying to store data having not enough permissions.

**Comment by keeganwitt** [comment]
This happens even if you change the user home, as shown in the GitLab documentation: https://gitlab.com/gitlab-org/gitlab-ce/blob/master/lib/gitlab/ci/templates/Gradle.gitlab-ci.yml

```yaml
before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
```

**Comment by jjinux** [comment]
If you created a user with the UID/GID from the environment, then people could pass that UID/GID, and you'd have access to the user's files without running as root. 

If you look at (https://hub.docker.com/_/gradle/), it says, "Note that if you are mounting a volume and the uid running Docker is not 1000, you should run as user root (-u root)." You could instead tell them to pass their UID/GID. This would be an improvement.

Bear in mind that I'm a Docker newb, so I could be wrong ;)

**Comment by keeganwitt** [comment]
You can already specify an arbitrary uid/gid, as long as you use a location that user/group can write, for example
`docker run --rm -u 197609 gradle gradle -g /tmp/.gradle --version`
or
`docker run --rm -u 197609 -e GRADLE_USER_HOME=/tmp/.gradle gradle gradle --version`

**Comment by disparo13** [comment]
> This happens even if you change the user home, as shown in the GitLab documentation (https://gitlab.com/gitlab-org/gitlab-ce/blob/master/lib/gitlab/ci/templates/Gradle.gitlab-ci.yml)?
That helped me now, thanks!

**Comment by keeganwitt** [comment]
I'm actually having trouble getting their example working in a vanilla Docker setup. I think this is the equivalent of their setup...

```bash
sudo groupadd -rg 9000 testuser
sudo useradd -mrg testuser -u 9000 -s /bin/bash testuser
sudo usermod -aG docker testuser
sudo su testuser
cd ~
mkdir .gradle/
docker run --rm -e GRADLE_USER_HOME=`pwd`/.gradle gradle gradle --build-cache --no-daemon --version
```

**Comment by tianon** [comment]
I found https://github.com/drone/drone/issues/363 which talks about adding `user:` to Drone's YAML syntax, but it looks like it was closed without ever being properly implemented and/or documented. :disappointed:

**Comment by keeganwitt** [comment]
I'm proceeding with defaulting the running user to root, but leaving the gradle user in the image, and recommending it's use wherever possible.
https://github.com/docker-library/official-images/pull/5857
https://github.com/docker-library/docs/pull/1487
